package com.xmitya.seafilesync.data.fs

/**
 * The rolling hash Seafile uses to decide where blocks end.
 *
 * A literal port of `common/cdc/rabin-checksum.c`. Nothing here is a reimplementation of the idea
 * -- the point is to land on the same block boundaries the desktop client does, and any deviation
 * simply produces different blocks, which costs deduplication rather than raising an error. The
 * tests check it against vectors generated by compiling that C file.
 *
 * Note the 32-bit truncation in [roll]: the checksum is carried as an unsigned int in the
 * original even though the table arithmetic is 64-bit, and keeping the wider value would give
 * different boundaries.
 */
object RabinFingerprint {

    private const val POLY = 0xbfe6b8a5bf378d83uL
    private const val MSB64 = 0x8000000000000000uL

    private val t = ULongArray(256)
    private val u = ULongArray(256)
    private var shift = 0

    /** [windowSize] must match the window the boundaries are scanned with. */
    fun init(windowSize: Int) {
        calcT(POLY)
        calcU(windowSize)
    }

    /** Checksum of a whole window, used to start each block. */
    fun checksum(buffer: ByteArray, offset: Int, length: Int): UInt {
        var sum = 0u
        for (i in 0 until length) sum = roll(sum, 0, buffer[offset + i])
        return sum
    }

    /** Advances the window by one byte: [leaving] falls out of it, [entering] joins it. */
    fun roll(checksum: UInt, leaving: Byte, entering: Byte): UInt =
        append8(checksum.toULong() xor u[leaving.toUByte().toInt()], entering).toUInt()

    private fun append8(p: ULong, m: Byte): ULong =
        ((p shl 8) or m.toUByte().toULong()) xor t[(p shr shift).toInt()]

    private fun calcT(poly: ULong) {
        val xshift = fls64(poly) - 1
        shift = xshift - 8
        val t1 = polymod(0uL, 1uL shl xshift, poly)
        for (j in 0..255) {
            t[j] = polymmult(j.toULong(), t1, poly) or (j.toULong() shl xshift)
        }
    }

    private fun calcU(size: Int) {
        var sizeshift = 1uL
        for (i in 1 until size) sizeshift = append8(sizeshift, 0)
        for (i in 0..255) u[i] = polymmult(i.toULong(), sizeshift, POLY)
    }

    /** Index of the highest set bit, plus one. */
    private fun fls64(v: ULong): Int = 64 - v.countLeadingZeroBits()

    private fun polymod(highIn: ULong, lowIn: ULong, divisor: ULong): ULong {
        var high = highIn
        var low = lowIn
        val k = fls64(divisor) - 1
        val d = divisor shl (63 - k)

        if (high != 0uL) {
            if ((high and MSB64) != 0uL) high = high xor d
            for (i in 62 downTo 0) {
                if ((high and (1uL shl i)) != 0uL) {
                    high = high xor (d shr (63 - i))
                    low = low xor (d shl (i + 1))
                }
            }
        }
        for (i in 63 downTo k) {
            if ((low and (1uL shl i)) != 0uL) low = low xor (d shr (63 - i))
        }
        return low
    }

    private fun polymult(x: ULong, y: ULong): Pair<ULong, ULong> {
        var high = 0uL
        var low = if ((x and 1uL) != 0uL) y else 0uL
        for (i in 1 until 64) {
            if ((x and (1uL shl i)) != 0uL) {
                high = high xor (y shr (64 - i))
                low = low xor (y shl i)
            }
        }
        return high to low
    }

    private fun polymmult(x: ULong, y: ULong, d: ULong): ULong {
        val (high, low) = polymult(x, y)
        return polymod(high, low, d)
    }
}
