package com.xmitya.seafilesync.ui.theme

import androidx.compose.ui.graphics.Color

/**
 * Tonal palette for the app, seeded from the launcher icon.
 *
 * Amber is the Seafile brand colour the icon mark is drawn in (#FFA10F); Navy is the icon's
 * background field (#14405F). Tones are the Material 3 stops, generated by sweeping L* in CIELCh
 * at a fixed hue with the chroma clamped back into sRGB, which is close enough to HCT for these
 * hues and needs no extra dependency. Regenerate with Material Theme Builder if exact HCT tones
 * ever matter.
 *
 * The suffix is the Material tone, so Amber40 is the amber hue at tone 40. That is what makes the
 * role assignments in SeafileSyncTheme readable against the Material 3 spec.
 */

internal val Amber10 = Color(0xFF291800)
internal val Amber20 = Color(0xFF472A00)
internal val Amber30 = Color(0xFF673D00)
internal val Amber40 = Color(0xFF875200)
internal val Amber70 = Color(0xFFF19700)
internal val Amber80 = Color(0xFFFFB867)
internal val Amber90 = Color(0xFFFFDCBB)
internal val Amber100 = Color(0xFFFFFFFF)

internal val Sand10 = Color(0xFF291800)
internal val Sand20 = Color(0xFF402D17)
internal val Sand30 = Color(0xFF58432C)
internal val Sand40 = Color(0xFF715A43)
internal val Sand80 = Color(0xFFDEC2A7)
internal val Sand90 = Color(0xFFFADEC2)
internal val Sand100 = Color(0xFFFFFFFF)

internal val Navy10 = Color(0xFF001E32)
internal val Navy20 = Color(0xFF003351)
internal val Navy30 = Color(0xFF154A6E)
internal val Navy40 = Color(0xFF346288)
internal val Navy80 = Color(0xFFA1CBF6)
internal val Navy90 = Color(0xFFCEE5FF)
internal val Navy100 = Color(0xFFFFFFFF)

internal val Neutral6 = Color(0xFF19120A)
internal val Neutral10 = Color(0xFF201B15)
internal val Neutral20 = Color(0xFF352F29)
internal val Neutral90 = Color(0xFFEAE1D9)
internal val Neutral95 = Color(0xFFF8EFE8)
internal val Neutral98 = Color(0xFFFFF8F2)

internal val NeutralVariant30 = Color(0xFF514438)
internal val NeutralVariant50 = Color(0xFF837567)
internal val NeutralVariant60 = Color(0xFF9D8E80)
internal val NeutralVariant80 = Color(0xFFD4C4B5)
internal val NeutralVariant90 = Color(0xFFF0E0D1)
