package com.xmitya.seafilesync.ui.theme

import androidx.compose.ui.graphics.Color

/**
 * Tonal palette for the app, seeded from the launcher icon.
 *
 * Amber is the Seafile brand colour the icon mark is drawn in (#FFA10F); Navy is the icon's
 * background field (#14405F). Tones are the Material 3 stops, generated by sweeping L* in CIELCh
 * at a fixed hue with the chroma clamped back into sRGB, which is close enough to HCT for these
 * hues and needs no extra dependency. Regenerate with Material Theme Builder if exact HCT tones
 * ever matter.
 *
 * The neutrals carry no chroma at all: tinting them towards the amber hue, as Material's own
 * generator does, turns every surface beige. The brand belongs on the accents, so the app sits on
 * plain white and grey instead.
 *
 * The suffix is the Material tone, so Amber40 is the amber hue at tone 40. That is what makes the
 * role assignments in SeafileSyncTheme readable against the Material 3 spec.
 */

internal val Amber10 = Color(0xFF291800)
internal val Amber20 = Color(0xFF472A00)
internal val Amber30 = Color(0xFF673D00)
internal val Amber40 = Color(0xFF875200)
internal val Amber70 = Color(0xFFF19700)
internal val Amber80 = Color(0xFFFFB867)
internal val Amber90 = Color(0xFFFFDCBB)
internal val Amber100 = Color(0xFFFFFFFF)

internal val Sand10 = Color(0xFF291800)
internal val Sand20 = Color(0xFF402D17)
internal val Sand30 = Color(0xFF58432C)
internal val Sand40 = Color(0xFF715A43)
internal val Sand80 = Color(0xFFDEC2A7)
internal val Sand90 = Color(0xFFFADEC2)
internal val Sand100 = Color(0xFFFFFFFF)

internal val Navy10 = Color(0xFF001E32)
internal val Navy20 = Color(0xFF003351)
internal val Navy30 = Color(0xFF154A6E)
internal val Navy40 = Color(0xFF346288)
internal val Navy80 = Color(0xFFA1CBF6)
internal val Navy90 = Color(0xFFCEE5FF)
internal val Navy100 = Color(0xFFFFFFFF)

internal val Neutral4 = Color(0xFF0F0F0F)
internal val Neutral6 = Color(0xFF141414)
internal val Neutral10 = Color(0xFF1B1B1B)
internal val Neutral12 = Color(0xFF1F1F1F)
internal val Neutral17 = Color(0xFF2A2A2A)
internal val Neutral20 = Color(0xFF303030)
internal val Neutral22 = Color(0xFF353535)
internal val Neutral24 = Color(0xFF3A3A3A)
internal val Neutral87 = Color(0xFFDEDEDE)
internal val Neutral90 = Color(0xFFE3E3E3)
internal val Neutral92 = Color(0xFFE9E9E9)
internal val Neutral94 = Color(0xFFEFEFEF)
internal val Neutral95 = Color(0xFFF2F2F2)
internal val Neutral96 = Color(0xFFF4F4F4)
internal val Neutral100 = Color(0xFFFFFFFF)

internal val NeutralVariant30 = Color(0xFF464646)
internal val NeutralVariant50 = Color(0xFF757575)
internal val NeutralVariant60 = Color(0xFF8F8F8F)
internal val NeutralVariant80 = Color(0xFFC7C7C7)
internal val NeutralVariant90 = Color(0xFFE2E2E2)
